// Auto-generated by LUTify.jl
// Testbench for tb_lut_bits8
// DUT:       lut_lut_bits8
// Entries:   64, Data width: 8-bit
// Tolerance: 1 ULP (quantization step)
// Range:     [-1.5707963267948966, 1.5707963267948966]

module tb_lut_bits8;

    parameter N      = 64;
    parameter BITS   = 8;
    parameter ADDR_W = 6;
    parameter TOLERANCE = 1;

    // DUT interface
    reg  [ADDR_W-1:0] addr;
    reg               clk;
    wire[BITS-1:0]    data;

    // Expected quantized reference (pre-computed by LUTify.jl)
    reg [BITS-1:0] expected [0:N-1];

    initial begin
        expected[000000] = 8'b00000000;
        expected[000001] = 8'b00000000;
        expected[000002] = 8'b00000001;
        expected[000003] = 8'b00000001;
        expected[000004] = 8'b00000011;
        expected[000005] = 8'b00000100;
        expected[000006] = 8'b00000110;
        expected[000007] = 8'b00001000;
        // indices 2-16
        expected[000008] = 8'b00001010;
        expected[000009] = 8'b00001101;
        expected[000010] = 8'b00010000;
        expected[000011] = 8'b00010011;
        expected[000012] = 8'b00010110;
        expected[000013] = 8'b00011010;
        expected[000014] = 8'b00011110;
        expected[000015] = 8'b00100010;
        // indices 10-24
        expected[000016] = 8'b00100110;
        expected[000017] = 8'b00101011;
        expected[000018] = 8'b00110000;
        expected[000019] = 8'b00110101;
        expected[000020] = 8'b00111010;
        expected[000021] = 8'b01000000;
        expected[000022] = 8'b01000101;
        expected[000023] = 8'b01001011;
        // indices 18-32
        expected[000024] = 8'b01010001;
        expected[000025] = 8'b01010111;
        expected[000026] = 8'b01011101;
        expected[000027] = 8'b01100011;
        expected[000028] = 8'b01101001;
        expected[000029] = 8'b01110000;
        expected[000030] = 8'b01110110;
        expected[000031] = 8'b01111100;
        // indices 26-40
        expected[000032] = 8'b10000011;
        expected[000033] = 8'b10001001;
        expected[000034] = 8'b10001111;
        expected[000035] = 8'b10010110;
        expected[000036] = 8'b10011100;
        expected[000037] = 8'b10100010;
        expected[000038] = 8'b10101000;
        expected[000039] = 8'b10101110;
        // indices 34-48
        expected[000040] = 8'b10110100;
        expected[000041] = 8'b10111010;
        expected[000042] = 8'b10111111;
        expected[000043] = 8'b11000101;
        expected[000044] = 8'b11001010;
        expected[000045] = 8'b11001111;
        expected[000046] = 8'b11010100;
        expected[000047] = 8'b11011001;
        // indices 42-56
        expected[000048] = 8'b11011101;
        expected[000049] = 8'b11100001;
        expected[000050] = 8'b11100101;
        expected[000051] = 8'b11101001;
        expected[000052] = 8'b11101100;
        expected[000053] = 8'b11101111;
        expected[000054] = 8'b11110010;
        expected[000055] = 8'b11110101;
        // indices 50-64
        expected[000056] = 8'b11110111;
        expected[000057] = 8'b11111001;
        expected[000058] = 8'b11111011;
        expected[000059] = 8'b11111100;
        expected[000060] = 8'b11111110;
        expected[000061] = 8'b11111110;
        expected[000062] = 8'b11111111;
        expected[000063] = 8'b11111111;
    end

    // DUT instantiation
    lut_lut_bits8 dut (
        .addr(addr),
        .clk(clk),
        .data(data)
    );

    // Clock: 10 time units period
    initial clk = 0;
    always #5 clk = ~clk;

    // Test driver
    integer i;
    integer errors;
    integer max_err;
    integer diff;

    initial begin
        errors   = 0;
        max_err  = 0;
        addr     = 6'b000000;
        #1;  // initial settle

        for (i = 0; i < N; i = i + 1) begin
            addr = i[ADDR_W-1:0];
            #10;  // capture on posedge clk
            if (integer'(data) !== integer'(expected[i])) begin
                errors = errors + 1;
                diff = integer'(data) - integer'(expected[i]);
                if (diff < 0) diff = -diff;
                if (diff > max_err) max_err = diff;
                $display('  ERROR addr=%0d: got=%0d expected=%0d err=%0d', i, integer'(data), integer'(expected[i]), diff);
            end
        end

        // Hold last address for 4 extra cycles (stability check)
        addr = 6'b000063;
            #10;
            if (integer'(data) !== integer'(expected[N-1])) begin
                errors = errors + 1;
                $display('  ERROR stable-check: got=%0d expected=%0d', integer'(data), integer'(expected[N-1]));
            end
            #10;
            if (integer'(data) !== integer'(expected[N-1])) begin
                errors = errors + 1;
                $display('  ERROR stable-check: got=%0d expected=%0d', integer'(data), integer'(expected[N-1]));
            end
            #10;
            if (integer'(data) !== integer'(expected[N-1])) begin
                errors = errors + 1;
                $display('  ERROR stable-check: got=%0d expected=%0d', integer'(data), integer'(expected[N-1]));
            end
            #10;
            if (integer'(data) !== integer'(expected[N-1])) begin
                errors = errors + 1;
                $display('  ERROR stable-check: got=%0d expected=%0d', integer'(data), integer'(expected[N-1]));
            end

    $display("========================================");
    $display("Testbench: tb_lut_bits8");
    $display("DUT:       lut_lut_bits8 (N=64, BITS=8)");
    $display('Cycles:    %d', total_cycles);
    $display('Errors:    %d / %d', errors, N);
    $display('Max err:   %d ULP', max_err);
    if (errors == 0) begin
        $display("RESULT: PASS -- all N entries match reference");
    end else begin
        $display('RESULT: FAIL -- %d mismatches detected', errors);
    end
    $display("========================================");

