##########################################################
# LUTify — HDL (Hardware Description Language) export
# Generate Verilog and VHDL modules from LUT objects
##########################################################

export export_verilog
export export_vhdl
export export_memfile

# _validate_bits(bits::Int) -> Nothing
# Validate that bits is between 1 and 32.
function _validate_bits(bits::Int)
    if bits < 1 || bits > 32
        error("bits must be between 1 and 32, got $bits")
    end
end

# _quantize_lut(lut::LUT, bits::Int) -> Vector{Int}
# Convert LUT float values to quantized integers in [0, 2^bits - 1].
# For LUT_cordic outputs (already in range), rounds to nearest integer.
# For standard LUTs (in [-1, 1]), linearly maps to [0, 2^bits-1].
function _quantize_lut(lut::LUT, bits::Int)
    scale = 2^bits - 1
    vals = Vector{Int}(undef, length(lut.lut))

    max_val = maximum(lut.lut)
    min_val = minimum(lut.lut)

    if max_val > 1.0 + eps()
        for (i, v) in enumerate(lut.lut)
            vals[i] = clamp(round(Int, v), 0, scale)
        end
    else
        range_val = max_val - min_val
        if range_val < eps()
            fill!(vals, scale ÷ 2)
        else
            for (i, v) in enumerate(lut.lut)
                vals[i] = clamp(round(Int, (v - min_val) / range_val * scale), 0, scale)
            end
        end
    end

    return vals
end

# export_verilog(lut::LUT, bits::Int=8, fn_name::String="lut") -> String
# Generate a Verilog module that implements the lookup table as a clocked memory.
# For single-variable LUTs, the address directly indexes into the table.
# For multi-variable LUTs, the address is the concatenation of per-variable
# address fields (big-endian: first var is MSB).
# Arguments:
#   - lut: a LUT object (from LUT() or LUT_cordic())
#   - bits: output bit-width (default 8)
#   - fn_name: module name suffix (default "lut")
# Returns the Verilog source as a string. Use `write("lut.v", export_verilog(...))` to save.
# Example:
# ```julia
# using LUTify
# sinlut = LUT_cordic(:sin, 0.0:(π/100):2π, 8, 16)
# open("sin_lut.v", "w") do f
#     write(f, export_verilog(sinlut, 8, "sin"))
# end
# ```
function export_verilog(lut::LUT, bits::Int=8, fn_name::String="lut")
    _validate_bits(bits)

    n = length(lut.lut)
    addr_bits = max(1, ceil(Int, log2(n)))
    addr_range = "$(addr_bits-1):0"
    data_range = "$(bits-1):0"
    module_name = "lut_$(fn_name)_bits$(bits)"

    vals = _quantize_lut(lut, bits)

    lines = String[]
    push!(lines, "// Auto-generated by LUTify.jl")
    push!(lines, "// Lookup table: $(n) entries, $(bits)-bit data width")
    push!(lines, "// Range: [$(lut.r[1]), $(lut.r[end])]")
    push!(lines, "")
    push!(lines, "module $(module_name)(")
    push!(lines, "    input  wire [$addr_range] addr,")
    push!(lines, "    input  wire                   clk,")
    push!(lines, "    output reg  [$data_range]     data")
    push!(lines, ");")
    push!(lines, "")

    push!(lines, "    // Lookup table memory")
    push!(lines, "    reg [$data_range] lut [0:$(n-1)];")
    push!(lines, "")

    push!(lines, "    initial begin")
    for (i, v) in enumerate(vals)
        idx_str = lpad(string(i-1), addr_bits, '0')
        val_str = _to_bin(v, bits)
        push!(lines, "        lut[$idx_str]  = $(bits)'b$val_str;")
    end
    push!(lines, "    end")
    push!(lines, "")

    push!(lines, "    // Clocked read")
    push!(lines, "    always @(posedge clk) begin")
    if n == 1
        push!(lines, "        data <= lut[0];")
    else
        push!(lines, "        data <= lut[addr];")
    end
    push!(lines, "    end")
    push!(lines, "")
    push!(lines, "endmodule")

    return join(lines, "\n")
end

# export_vhdl(lut::LUT, bits::Int=8, fn_name::String="lut") -> String
# Generate a VHDL entity/architecture that implements the lookup table.
# Arguments:
#   - lut: a LUT object
#   - bits: output bit-width (default 8)
#   - fn_name: entity name suffix (default "lut")
# Returns the VHDL source as a string.
# Example:
# ```julia
# open("sin_lut.vhd", "w") do f
#     write(f, export_vhdl(sinlut, 8, "sin"))
# end
# ```
function export_vhdl(lut::LUT, bits::Int=8, fn_name::String="lut")
    _validate_bits(bits)

    n = length(lut.lut)
    addr_bits = max(1, ceil(Int, log2(n)))
    addr_range = "$(addr_bits-1)"
    data_range = "$(bits-1)"
    entity_name = "lut_$(fn_name)_$(bits)bit"

    vals = _quantize_lut(lut, bits)

    lines = String[]
    push!(lines, "-- Auto-generated by LUTify.jl")
    push!(lines, "-- Lookup table: $(n) entries, $(bits)-bit data width")
    push!(lines, "-- Range: [$(lut.r[1]), $(lut.r[end])]")
    push!(lines, "")
    push!(lines, "library ieee;")
    push!(lines, "use ieee.std_logic_1164.all;")
    push!(lines, "use ieee.numeric_std.all;")
    push!(lines, "")
    push!(lines, "entity $(entity_name) is")
    push!(lines, "    port (")
    push!(lines, "        addr : in  std_logic_vector($addr_range downto 0);")
    push!(lines, "        clk  : in  std_logic;")
    push!(lines, "        data : out std_logic_vector($data_range downto 0)")
    push!(lines, "    );")
    push!(lines, "end entity $(entity_name);")
    push!(lines, "")
    push!(lines, "architecture rtl of $(entity_name) is")
    push!(lines, "")

    push!(lines, "    type lut_array_t is array (natural range 0 to $(n-1)) of ")
    push!(lines, "        unsigned($data_range downto 0);")
    push!(lines, "")

    push!(lines, "    constant lut : lut_array_t := (")
    for (i, v) in enumerate(vals)
        idx_str = lpad(string(i-1), addr_bits, '0')
        hex_val = lowercase(string(v, base=16))
        while length(hex_val) < ceil(Int, bits / 4)
            hex_val = "0" * hex_val
        end
        comma = i < n ? "," : ";"
        push!(lines, "        $(idx_str) => x\"$hex_val\",")
    end
    push!(lines, "        others => (others => '0');")
    push!(lines, "    );")
    push!(lines, "")

    push!(lines, "begin")
    push!(lines, "")
    push!(lines, "    process(clk) begin")
    push!(lines, "        if rising_edge(clk) then")
    push!(lines, "            data <= std_logic_vector(lut(to_integer(unsigned(addr))));")
    push!(lines, "        end if;")
    push!(lines, "    end process;")
    push!(lines, "")
    push!(lines, "end architecture rtl;")

    return join(lines, "\n")
end

# export_memfile(lut::LUT, path::String; bits::Int=8, format::Symbol=:hex) -> Nothing
# Write a memory initialization file for FPGA tools.
# Supported formats:
#   - :hex — Intel/Altera HEX format (default)
#   - :mif — Altera MIF (Memory Initialization File) format
#   - :coe — Xilinx COE (Coefficient) format
#   - :txt — Simple one-value-per-line text
# Arguments:
#   - lut: a LUT object
#   - path: file path to write to
#   - bits: output bit-width (default 8)
#   - format: output format symbol
# Example:
# ```julia
# export_memfile(sinlut, "sin_lut.hex")
# export_memfile(sinlut, "sin_lut.coe"; bits=16, format=:coe)
# ```
function export_memfile(lut::LUT, path::String; bits::Int=8, format::Symbol=:hex)
    _validate_bits(bits)

    n = length(lut.lut)
    vals = _quantize_lut(lut, bits)

    open(path, "w") do io
        if format == :hex
            println(io, "% $(bits)")
            println(io, "$n")
            for v in vals
                hex_str = lowercase(string(v, base=16))
                while length(hex_str) < ceil(Int, bits / 4)
                    hex_str = "0" * hex_str
                end
                println(io, hex_str)
            end
        elseif format == :mif
            width_bits = max(1, ceil(Int, log2(n)))
            println(io, "DEPTH = $n;")
            println(io, "WIDTH = $bits;")
            println(io, "ADDRESS_RADIX = UNS;")
            println(io, "DATA_RADIX = BIN;")
            println(io, "CONTENT")
            println(io, "BEGIN")
            for (i, v) in enumerate(vals)
                idx_str = lpad(string(i-1), width_bits, '0')
                bin_str = string(v, base=2)
                while length(bin_str) < bits
                    bin_str = "0" * bin_str
                end
                println(io, "\t$idx_str : $bin_str;")
            end
            println(io, "END;")
        elseif format == :coe
            println(io, "memory_initialization_radix=10;")
            println(io, "memory_initialization_vector=")
            for (i, v) in enumerate(vals)
                comma = i < n ? "," : ";"
                sep = i < n ? "," : ";"
                println(io, "    $v$sep")
            end
        elseif format == :txt
            for v in vals
                println(io, v)
            end
        else
            error("Unsupported format: $format. Use :hex, :mif, :coe, or :txt")
        end
    end

    return nothing
end

# _to_hex(n::Int, width::Int) -> String
# Convert integer to zero-padded lowercase hex string of given width.
function _to_hex(n::Int, width::Int)::String
    s = lowercase(string(n, base=16))
    return length(s) < width ? repeat("0", width - length(s)) * s : s
end

# _to_bin(n::Int, width::Int) -> String
# Convert integer to zero-padded binary string of given width.
function _to_bin(n::Int, width::Int)::String
    s = string(n, base=2)
    return length(s) < width ? repeat("0", width - length(s)) * s : s
end

##############################################################
# export_testbench(lut::LUT, bits::Int=8, fn_name::String="lut";
#                  tolerance::Real=1.0) -> String
##############################################################
function export_testbench(
    lut::LUT, bits::Int=8, fn_name::String="lut";
    tolerance::Real=1.0, extra_cycles::Int=4
)::String

    _validate_bits(bits)
    n = length(lut.lut)
    addr_bits = max(1, ceil(Int, log2(n)))
    scale = 2^bits - 1
    module_name = "lut_$(fn_name)_bits$(bits)"
    tb_name = "tb_$(fn_name)_bits$(bits)"
    lut_vals = _quantize_lut(lut, bits)
    ref_vals = Vector{Int}(undef, n)
    r_start = Float64(lut.r[1])
    r_end   = Float64(lut.r[end])
    step    = (n > 1) ? (r_end - r_start) / (n - 1) : 0.0

    for i in 1:n
        theta = r_start + (i - 1) * step
        ref_val = _ref_function(lut.f, theta)
        q = round(Int, (clamp(ref_val, -1.0, 1.0) + 1.0) / 2.0 * scale)
        ref_vals[i] = clamp(q, 0, scale)
    end

    io = IOBuffer()
    println(io, "// Auto-generated by LUTify.jl")
    println(io, "// Testbench for ", tb_name)
    println(io, "// DUT:       ", module_name)
    println(io, "// Entries:   ", n, ", Data width: ", bits, "-bit")
    println(io, "// Tolerance: ", Int(tolerance), " ULP (quantization step)")
    println(io, "// Range:     [", r_start, ", ", r_end, "]")
    println(io, "")
    println(io, "module ", tb_name, ";")
    println(io, "")
    println(io, "    parameter N      = ", n, ";")
    println(io, "    parameter BITS   = ", bits, ";")
    println(io, "    parameter ADDR_W = ", addr_bits, ";")
    println(io, "    parameter TOLERANCE = ", Int(tolerance), ";")
    println(io, "")
    println(io, "    // DUT interface")
    println(io, "    reg  [ADDR_W-1:0] addr;")
    println(io, "    reg               clk;")
    println(io, "    wire[BITS-1:0]    data;")
    println(io, "")
    println(io, "    // Expected quantized reference (pre-computed by LUTify.jl)")
    println(io, "    reg [BITS-1:0] expected [0:N-1];")
    println(io, "")
    println(io, "    initial begin")
    for i in 1:n
        val_str = _to_bin(ref_vals[i], bits)
        idx_str = lpad(string(i-1), addr_bits, '0')
        if (i - 1) % 8 == 0 && i > 1
            println(io, "        // indices ", min(i, n)-7, "-", min(i+7, n))
        end
        println(io, "        expected[", idx_str, "] = ", bits, "'b", val_str, ";")
    end
    println(io, "    end")
    println(io, "")
    println(io, "    // DUT instantiation")
    println(io, "    ", module_name, " dut (")
    println(io, "        .addr(addr),")
    println(io, "        .clk(clk),")
    println(io, "        .data(data)")
    println(io, "    );")
    println(io, "")
    println(io, "    // Clock: 10 time units period")
    println(io, "    initial clk = 0;")
    println(io, "    always #5 clk = ~clk;")
    println(io, "")
    total_cycles = n + extra_cycles
    println(io, "    // Test driver")
    println(io, "    integer i;")
    println(io, "    integer errors;")
    println(io, "    integer max_err;")
    println(io, "    integer diff;")
    println(io, "")
    println(io, "    initial begin")
    println(io, "        errors   = 0;")
    println(io, "        max_err  = 0;")
    println(io, "        addr     = ", addr_bits, "'b", repeat("0", addr_bits), ";")
    println(io, "        #1;  // initial settle")
    println(io, "")
    println(io, "        for (i = 0; i < N; i = i + 1) begin")
    println(io, "            addr = i[ADDR_W-1:0];")
    println(io, "            #10;  // capture on posedge clk")
    println(io, "            if (integer'(data) !== integer'(expected[i])) begin")
    println(io, "                errors = errors + 1;")
    println(io, "                diff = integer'(data) - integer'(expected[i]);")
    println(io, "                if (diff < 0) diff = -diff;")
    println(io, "                if (diff > max_err) max_err = diff;")
    println(io, "                \$display('  ERROR addr=%0d: got=%0d expected=%0d err=%0d', i, integer'(data), integer'(expected[i]), diff);")
    println(io, "            end")
    println(io, "        end")
    println(io, "")
    if extra_cycles > 0
        last_addr = lpad(string(n-1), addr_bits, '0')
        println(io, "        // Hold last address for ", extra_cycles, " extra cycles (stability check)")
        println(io, "        addr = ", addr_bits, "'b", last_addr, ";")
        for _ in 1:extra_cycles
            println(io, "            #10;")
            println(io, "            if (integer'(data) !== integer'(expected[N-1])) begin")
            println(io, "                errors = errors + 1;")
            println(io, "                \$display('  ERROR stable-check: got=%0d expected=%0d', integer'(data), integer'(expected[N-1]));")
            println(io, "            end")
        end
        println(io, "")
    end
    # Report results
    println(io, "    \$display('========================================');")
    println(io, "    \$display('Testbench: ", tb_name, "');")
    println(io, "    \$display('DUT:       ", module_name, " (N=", n, ", BITS=", bits, ")');")
    println(io, "    \$display('Cycles:    %d', total_cycles);")
    println(io, "    \$display('Errors:    %d / %d', errors, N);")
    println(io, "    \$display('Max err:   %d ULP', max_err);")
    println(io, "    if (errors == 0) begin")
    println(io, "        \$display('RESULT: PASS -- all N entries match reference');")
    println(io, "    end else begin")
    println(io, "        \$display('RESULT: FAIL -- %d mismatches detected', errors);")
    println(io, "    end")
    println(io, "    \$display('========================================');")
    println(io, "")

    return String(take!(io))
end


function _ref_function(fn, θ::Float64)::Float64
    # Handle Symbol (e.g., :sin, :cos)
    if fn isa Symbol
        if fn == :sin
            return sin(θ)
        elseif fn == :cos
            return cos(θ)
        elseif fn == :tan
            return tan(θ)
        else
            error("Unsupported function for testbench reference: ", fn)
        end
    # Handle Function (e.g., sin, cos from standard LUTs or closures)
    elseif fn isa Function
        # Try to get the function name safely
        fname = try
            hasfield(typeof(fn), :name) ? fn.name : nothing
        catch
            nothing
        end
        if fname === Symbol("sin")
            return sin(θ)
        elseif fname === Symbol("cos")
            return cos(θ)
        elseif fname === Symbol("tan")
            return tan(θ)
        else
            # For anonymous functions (like LUT_cordic closures), just call it directly
            return fn(θ)
        end
    else
        error("Unsupported function type for testbench reference: ", typeof(fn))
    end
end
